server:
  port: 8087

spring:
  r2dbc:
    url: r2dbc:postgresql://ep-sweet-cherry-ac1jujjy-pooler.sa-east-1.aws.neon.tech/requestsservice?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_JPQSp1e0TCj0
  codec:
    max-in-memory-size: 20MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://lab.vallegrande.edu.pe:8180/realms/fideinexus
          jwk-set-uri: http://lab.vallegrande.edu.pe:8180/realms/fideinexus/protocol/openid-connect/certs

logging:
  level:
    org.springframework.r2dbc: DEBUG

services:
  sacrament:
    url: http://lab.vallegrande.edu.pe:8083
  community:
    url: http://lab.vallegrande.edu.pe:8090

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
