server:
  port: ${PORT:8085}

spring:
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://ep-sweet-cherry-ac1jujjy-pooler.sa-east-1.aws.neon.tech/requestsservice?sslmode=require&channel_binding=require}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_JPQSp1e0TCj0}
  codec:
    max-in-memory-size: 20MB

logging:
  level:
    org.springframework.r2dbc: DEBUG

services:
  sacrament:
    url: ${SACRAMENT_SERVICE_URL:http://localhost:8086}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
