-- =============================================
-- REQUESTS SERVICE - DATA
-- Los tipos de solicitud son creados por cada
-- tenant (parroquia) desde la interfaz.
-- =============================================
