-- =============================================
-- REQUESTS SERVICE - DATA
-- Categorías de solicitud fijas (no configurables por tenant):
--   MISA            → Reserva de misa
--   ACTA_SACRAMENTAL → Acta de sacramento (Bautismo, Eucaristía, Confirmación, Matrimonio)
--   SACRAMENTO      → Inscripción/registro para recibir un sacramento
--
-- Tipos de sacramento (sacrament_type):
--   BAUTISMO | EUCARISTIA | CONFIRMACION | MATRIMONIO
-- =============================================
