-- =============================================
-- REQUESTS SERVICE - DATA
-- No hay datos iniciales.
-- Los tipos de solicitud (misas y sacramentos)
-- se obtienen en tiempo real desde los microservicios
-- de los compañeros via el backend proxy.
-- =============================================
